version: '3.9'

services:
  holded-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/var/www/holded-service
    working_dir: /var/www/holded-service
    environment:
      APP_ENV: dev
    networks:
      - symfony

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/holded-service
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - holded-service
    networks:
      - symfony

networks:
  symfony:
    driver: bridge